export {
  body,
  blockTitle,
  calloutColumns,
  contentBlockLabel,
  editorialSplit,
  figureRow12,
  figureRow12Cell,
  figureRow12Cell4,
  h1,
  h2,
  halfColumns,
  halfColumnsContent,
  halfColumnsLabel,
  heroIntroBody,
  heroIntroSplit,
  heroLead,
  introH4,
  metaItemLabel,
  metaLabel,
  scenarioColumns,
  screenTitle,
  subsectionStack,
  subsectionStack64,
  subsectionTitle,
} from "@/components/project/cococare/constants";
