/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkWithMeRouteImport } from './routes/work-with-me'
import { Route as WeldRouteImport } from './routes/weld'
import { Route as RokokowebRouteImport } from './routes/rokokoweb'
import { Route as RokokobrandRouteImport } from './routes/rokokobrand'
import { Route as PowermatchRouteImport } from './routes/powermatch'
import { Route as PlintoRouteImport } from './routes/plinto'
import { Route as EatgrimRouteImport } from './routes/eatgrim'
import { Route as CococareRouteImport } from './routes/cococare'
import { Route as AgerasRouteImport } from './routes/ageras'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const WorkWithMeRoute = WorkWithMeRouteImport.update({
  id: '/work-with-me',
  path: '/work-with-me',
  getParentRoute: () => rootRouteImport,
} as any)
const WeldRoute = WeldRouteImport.update({
  id: '/weld',
  path: '/weld',
  getParentRoute: () => rootRouteImport,
} as any)
const RokokowebRoute = RokokowebRouteImport.update({
  id: '/rokokoweb',
  path: '/rokokoweb',
  getParentRoute: () => rootRouteImport,
} as any)
const RokokobrandRoute = RokokobrandRouteImport.update({
  id: '/rokokobrand',
  path: '/rokokobrand',
  getParentRoute: () => rootRouteImport,
} as any)
const PowermatchRoute = PowermatchRouteImport.update({
  id: '/powermatch',
  path: '/powermatch',
  getParentRoute: () => rootRouteImport,
} as any)
const PlintoRoute = PlintoRouteImport.update({
  id: '/plinto',
  path: '/plinto',
  getParentRoute: () => rootRouteImport,
} as any)
const EatgrimRoute = EatgrimRouteImport.update({
  id: '/eatgrim',
  path: '/eatgrim',
  getParentRoute: () => rootRouteImport,
} as any)
const CococareRoute = CococareRouteImport.update({
  id: '/cococare',
  path: '/cococare',
  getParentRoute: () => rootRouteImport,
} as any)
const AgerasRoute = AgerasRouteImport.update({
  id: '/ageras',
  path: '/ageras',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ageras': typeof AgerasRoute
  '/cococare': typeof CococareRoute
  '/eatgrim': typeof EatgrimRoute
  '/plinto': typeof PlintoRoute
  '/powermatch': typeof PowermatchRoute
  '/rokokobrand': typeof RokokobrandRoute
  '/rokokoweb': typeof RokokowebRoute
  '/weld': typeof WeldRoute
  '/work-with-me': typeof WorkWithMeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ageras': typeof AgerasRoute
  '/cococare': typeof CococareRoute
  '/eatgrim': typeof EatgrimRoute
  '/plinto': typeof PlintoRoute
  '/powermatch': typeof PowermatchRoute
  '/rokokobrand': typeof RokokobrandRoute
  '/rokokoweb': typeof RokokowebRoute
  '/weld': typeof WeldRoute
  '/work-with-me': typeof WorkWithMeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ageras': typeof AgerasRoute
  '/cococare': typeof CococareRoute
  '/eatgrim': typeof EatgrimRoute
  '/plinto': typeof PlintoRoute
  '/powermatch': typeof PowermatchRoute
  '/rokokobrand': typeof RokokobrandRoute
  '/rokokoweb': typeof RokokowebRoute
  '/weld': typeof WeldRoute
  '/work-with-me': typeof WorkWithMeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ageras'
    | '/cococare'
    | '/eatgrim'
    | '/plinto'
    | '/powermatch'
    | '/rokokobrand'
    | '/rokokoweb'
    | '/weld'
    | '/work-with-me'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ageras'
    | '/cococare'
    | '/eatgrim'
    | '/plinto'
    | '/powermatch'
    | '/rokokobrand'
    | '/rokokoweb'
    | '/weld'
    | '/work-with-me'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ageras'
    | '/cococare'
    | '/eatgrim'
    | '/plinto'
    | '/powermatch'
    | '/rokokobrand'
    | '/rokokoweb'
    | '/weld'
    | '/work-with-me'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AgerasRoute: typeof AgerasRoute
  CococareRoute: typeof CococareRoute
  EatgrimRoute: typeof EatgrimRoute
  PlintoRoute: typeof PlintoRoute
  PowermatchRoute: typeof PowermatchRoute
  RokokobrandRoute: typeof RokokobrandRoute
  RokokowebRoute: typeof RokokowebRoute
  WeldRoute: typeof WeldRoute
  WorkWithMeRoute: typeof WorkWithMeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work-with-me': {
      id: '/work-with-me'
      path: '/work-with-me'
      fullPath: '/work-with-me'
      preLoaderRoute: typeof WorkWithMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weld': {
      id: '/weld'
      path: '/weld'
      fullPath: '/weld'
      preLoaderRoute: typeof WeldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rokokoweb': {
      id: '/rokokoweb'
      path: '/rokokoweb'
      fullPath: '/rokokoweb'
      preLoaderRoute: typeof RokokowebRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rokokobrand': {
      id: '/rokokobrand'
      path: '/rokokobrand'
      fullPath: '/rokokobrand'
      preLoaderRoute: typeof RokokobrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/powermatch': {
      id: '/powermatch'
      path: '/powermatch'
      fullPath: '/powermatch'
      preLoaderRoute: typeof PowermatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plinto': {
      id: '/plinto'
      path: '/plinto'
      fullPath: '/plinto'
      preLoaderRoute: typeof PlintoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eatgrim': {
      id: '/eatgrim'
      path: '/eatgrim'
      fullPath: '/eatgrim'
      preLoaderRoute: typeof EatgrimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cococare': {
      id: '/cococare'
      path: '/cococare'
      fullPath: '/cococare'
      preLoaderRoute: typeof CococareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ageras': {
      id: '/ageras'
      path: '/ageras'
      fullPath: '/ageras'
      preLoaderRoute: typeof AgerasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AgerasRoute: AgerasRoute,
  CococareRoute: CococareRoute,
  EatgrimRoute: EatgrimRoute,
  PlintoRoute: PlintoRoute,
  PowermatchRoute: PowermatchRoute,
  RokokobrandRoute: RokokobrandRoute,
  RokokowebRoute: RokokowebRoute,
  WeldRoute: WeldRoute,
  WorkWithMeRoute: WorkWithMeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
